### ISSUE TITLE
Multi Account not working. 

### ISSUE THREAD

**Issue by Blackfoxx88** [bhrama-br/spacecrypto-bombcrypto-bot#2]
Hi, Single account is working great, after i changed the images.

However, i wanted to use Multi account.

After enabling Multi account, and doing all the instructions regarding Flags on brave.

The bot reads the profile names. But says ot has 0 profiles.

**Comment by bhrama-br** [comment]
I can't test multiple accounts. because I don't have 2 accounts.

But it was supposed to work.

**Comment by Blackfoxx88** [comment]
Sorry posted on the Wrong thread. Thank you.
