### ISSUE TITLE
Scritp nao esta movendo o cursor!

### ISSUE THREAD

**Issue by ruskye** [bhrama-br/spacecrypto-bombcrypto-bot#3]
Configurei todo o python, as imagens, o scrpit tenta funcionar, mas nao esta movendo o cursor, o que pode ser?

**Comment by bhrama-br** [comment]
Fiz um commit. Valide qual e sua Resolução! caso seja diferente de 1920.  Tente colocar 150% e muda as imagens!

Entra no Discord que posso tentar ajudar melhor!
