### ISSUE TITLE
I dont have bombcrypto

### ISSUE THREAD

**Issue by gfbalielo** [bhrama-br/spacecrypto-bombcrypto-bot#4]
Hy, i only have space crypto and i like so much your bot code, so, could i use just Space Crypto with this?

**Comment by bhrama-br** [comment]
Yes, and just leave the spacecrypt screen open!

**Comment by gfbalielo** [comment]
Nice, thank you! so, in code i need put False?
multiples_accounts_same_monitor:
  enable: True
  window_contains_title: "bombcrypto"
  
  sorry to ask it, i'm new and i'm tryning config it. Do i need change something more?

**Comment by bhrama-br** [comment]
No need, just configure where this space:

**Comment by gfbalielo** [comment]
sorry i dont understand

**Comment by bhrama-br** [comment]
> sorry i dont understand

Update the space in archive config.yaml

  ###### True for Resolution 1920x1080, False for 1600x900
  checkResolution: True

`space:
  ###### True para Resolução 1920x1080, False para 1600x900
  checkResolution: True

  check_ship_to_fight: 20
  check_ship_tela_boss: 21
  qtScroll: 7`

**Comment by bhrama-br** [comment]
@gbailinho 
one helps the other there.

https://discord.gg/ahwf3Nfd
