### ISSUE TITLE
SURRENDER - É possivel selecionar boss para SURRENDER?

### ISSUE THREAD

**Issue by evertonurbanii** [bhrama-br/spacecrypto-bombcrypto-bot#5]
Boa tarde!
É possivel selecionar boss para SURRENDER?

**Comment by bhrama-br** [comment]
no momento não! e a próxima função que irei criar!

**Comment by evertonurbanii** [comment]
Ai vai ser o bot mais completo atualmente, tem alguma previsão?
todos q encontrei.. ou faz seleção de BOSS ou é multaccount.. rsrs

**Comment by bhrama-br** [comment]
Talvez amanha.

**Comment by evertonurbanii** [comment]
perfeito.. brigadao

**Comment by bhrama-br** [comment]
Surrender está implementado.
