### ISSUE TITLE
Bot travado

### ISSUE THREAD

**Issue by rodrigorscb** [bhrama-br/spacecrypto-bombcrypto-bot#6]
Boa tarde,

Segui as instruções para usar em 1 navegador apenas o spacecrypto, porém ele conecta mas quando chega na tela das naves fica dizendo:

←[92m[2022-02-18 18:24:56] => Client active window: Space Crypto - Google Chrome←[0m
Ship continue
←[99m[2022-02-18 18:25:04] => ⬆️ Processing last action..
←[92m[2022-02-18 18:25:05] => Client active window: Space Crypto - Google Chrome←[0m
Ship continue
←[99m[2022-02-18 18:25:13] => ⬆️ Processing last action..
←[92m[2022-02-18 18:25:14] => Client active window: Space Crypto - Google Chrome←[0m
Ship continue
←[99m[2022-02-18 18:25:22] => ⬆️ Processing last action..
←[92m[2022-02-18 18:25:23] => Client active window: Space Crypto - Google Chrome←[0m
Verificando se o jogo foi desconectado
Ship continue
←[99m[2022-02-18 18:25:43] => ⬆️ Processing last action..
←[92m[2022-02-18 18:25:44] => Client active window: Space Crypto - Google Chrome←[0m
Ship continue
←[99m[2022-02-18 18:25:52] => ⬆️ Processing last action..

Alguma sugestão?

**Comment by bhrama-br** [comment]
Na primeira vez q ligou o bot. Ele selecionou as naves?

Caso não, tente atualizar as imagens.

**Comment by rodrigorscb** [comment]
> Na primeira vez q ligou o bot. Ele selecionou as naves?
> 
> Caso não, tente atualizar as imagens.
nao selecionou nao…
alterei a imagem do fight e nada…vou tentar atualizar todas

**Comment by bhrama-br** [comment]
Então, Coloca o navegador em 150% e muda as imagens que e pra funcionar,  Subi uma versão hoje cedo!

**Comment by rodrigorscb** [comment]
Troquei as imagens no 100% mesmo rodou liso, valeu!!
