### ISSUE TITLE
Duvida: Eu tenho bomb e space, ele roda os dois é isso?

### ISSUE THREAD

**Issue by olivete** [bhrama-br/spacecrypto-bombcrypto-bot#7]
Olá!

Primeiro, obrigado pelo esforço!!!

Segundo: Eu tenho 5 contas do bomber e 3 do space, no caso basta eu deixar o chrome aberto e maximizado com esse total de 8 contas e o bot vai rotacionando é isso?

Desculpe se aqui nao é pra duvida, mas eu nao sabia onde postar :)

Muito obrigado!

**Comment by bhrama-br** [comment]
Não pode esta em Abas.
Não testei em multi contas no space. mas e pra funcionar sim!
