### ISSUE TITLE
Problema com nave. Se a primeira nao tem energia ele fica travado

### ISSUE THREAD

**Issue by olivete** [bhrama-br/spacecrypto-bombcrypto-bot#8]
Opa!!!

Camarada, obrigado por manter esse maravilhoso bot. Comecei a usar ontem pra 4 contas do bomber e 3 do SPG.

O bomber pelo o notei, ta liso, ja o SPG ta dando uns problemas.

Atualmente o princial erro que to tendo é que minha primeira nave é Lendaria, entao geralmetne fica no topo da lista. Se essa primeira nave nao tem energia, o bot fica tentando por ela pra trabalhar e ai nao faz mais nada.

Screenshot: https://imgur.com/IKEClbV

Ele detecta outros botoes, diz que ta enviando as naves, mas o mouse fica travado em cima do primeiro botao de "fight" apagado. Dai ele passa pra proxima conta, e essa conta ai fica parada.

Eu to usando 1080, aumentei a parte do scan de imagem de 0.9 pra 0.95, mas o danado continua clicando nesse FIGHT apagado ai.

Alguma sugestao? Muito obrigado!!!

**Comment by bhrama-br** [comment]
Opa, que bom que gostou :D

Este erro e a Imagem.. tente atualizar a imagem do fight.

Estou on mais no Discord. qualquer coisa entra la.

**Comment by olivete** [comment]
Vou tentar mudar aqui e dai logo la, pior que atualizei tudo que foi imagem ontem, so pra garantir.

Ja te dou um feedback, valeu ai por responder tao rapido!!!

**Comment by bhrama-br** [comment]
qualquer coisa, pode tentar aumentar a scala tbm. para 150%

**Comment by olivete** [comment]
Desculpa a demora pra responder, simplesmente deu outro erro agora ahahahahah
Eu abro o bot, e ai ele comecou a reclamar do requirement la o Pywindow.... a unica coisa que mexi foi literalmente mudar a imagem e o treshold de 0.9 pra 0.95. O treshold eu voltei pra 0.9.

Acho que vou baixar de novo, tentar fazer tudo do zero aqui pra ver se funciona. Fiz alguma cagada, o que foi, eu nao sei aeuhaeuaheuehueh

**Comment by olivete** [comment]
Rapaz, deu problema mesmo!

Baixei o zip de novo, rodei o requirements., etc

https://imgur.com/c8mfz9R

ta dando esse erro.

Desde ontem tava rodando tudo liso... agora nao entendi nada!

Ja reiniciei o PC, ja fechei o chrome e reloguei em todas contas... nao entendo como aconteceu isso simplesmente entre uma pausa no uso e outra :(((

PS: O invite do disc ta expirado :(

**Comment by bhrama-br** [comment]
[Link Discord](https://discord.gg/4gMA5Nhxrb)

**Comment by bhrama-br** [comment]
Resolvido! :D
